"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['src/main.py']
DATA_FILES = []
OPTIONS = {
    'packages': ['src', 'pynput', 'uvicorn', 'rumps', 'fastapi'],
    'includes': ['pynput', 'uvicorn', 'rumps', 'fastapi']
}

setup(
    name="RootFriends",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
